steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone
        "$_ZONE" --project "$_PROJECT_ID"
    entrypoint: bash
  ### Build
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld', '.']
    
    
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: 
      - "-c"
      - "gcloud container images describe 'gcr.io/$_PROJECT_ID/helloworld' '--format' 'value(image_summary.digest)' > sha"
     
    
  
  - id: 'create-attestation'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - '--artifact-url'
      - 'gcr.io/${PROJECT_ID}/helloworld'
      - '--attestor'
      - 'projects/${PROJECT_ID}/attestors/$_ATTESTOR_NAME'
      - '--keyversion'
      - 'projects/${PROJECT_ID}/locations/$_KMS_KEY_LOCATION/keyRings/$_KMS_KEYRING_NAME/cryptoKeys/$_KMS_KEY_NAME/cryptoKeyVersions/$_KMS_KEY_VERSION'
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: 
      - "-c"
      - >-
        'gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone'
        "$_ZONE" --project "$_PROJECT_ID"
    
  - name: "gcr.io/cloud-builders/gke-deploy"
    args: 
      - run
      - --image=gcr.io/$_PROJECT_ID/helloworld:$_TAG
      - --location=$_ZONE
      - --cluster=$_CLUSTER_NAME 
