steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone
        "$_ZONE" --project "$_PROJECT_ID"
    entrypoint: bash
  ### Build
  - name: gcr.io/cloud-builders/gcloud
    id: Build-Docker-Image
    args:
      - builds
      - submit
      - '--region=us-central1'
      - '--tag'
      - >-
        us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/helloworld:$_TAG
    
  
    
    
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: 
      - "-c"
      - "gcloud container images describe 'gcr.io/$_PROJECT_ID/helloworld' '--format' 'value(image_summary.digest)' > sha"
     
    
  
  - id: 'create-attestation'
    name: 'gcr.io/$PROJECT_ID/binauthz-attestation:latest'
    args:
      - '--artifact-url'
      - 'gcr.io/${PROJECT_ID}/helloworld:$_TAG'
      - '--attestor'
      - 'projects/${PROJECT_ID}/attestors/$_ATTESTOR_NAME'
      - '--keyversion'
      - 'projects/${PROJECT_ID}/locations/$_KMS_KEY_LOCATION/keyRings/$_KMS_KEYRING_NAME/cryptoKeys/$_KMS_KEY_NAME/cryptoKeyVersions/$_KMS_KEY_VERSION'
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: 
      - "-c"
      - >-
        'gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone'
        "$_ZONE" --project "$_PROJECT_ID"
    
  - name: "gcr.io/cloud-builders/gke-deploy"
    args: 
      - run
      - --image=gcr.io/$_PROJECT_ID/helloworld:$_TAG
      - --location=$_ZONE
      - --cluster=$_CLUSTER_NAME 
