steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/helloworld:latest'
      - '.'
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/helloworld:latest'
  - id: 'attest'
    name: 'gcr.io/$PROJECT_ID/binauthz-attestation:latest'
    args:
      - '--attestor'
      - 'projects/$PROJECT_ID/attestors/my-cloudbuildkey'
      - '--artifact-url'
      - 'gcr.io/$PROJECT_ID/helloworld:latest'
      - '--keyversion'
      - 'projects/$PROJECT_ID/locations/global/keyRings/my-cloudbuildkey/cryptoKeys/my-cloudbuildkey/cryptoKeyVersions/1'
tags: ['cloud-builders-community']
