steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone
        "$_ZONE" --project "$_PROJECT_ID"
    entrypoint: bash
    

  - id: 'build-docker-image'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - builds
      - submit
      - '--region=us-central1'
      - '--tag'
      - >-
        us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/test-image:$_TAG

  - id: 'create-attestation'
    name: 'gcr.io/$PROJECT_ID/binauthz-attestation:latest'
    args:
      - '--attestor'
      - 'projects/${PROJECT_ID}/attestors/$_ATTESTOR_NAME'
      - '--keyversion'
      - 'projects/${PROJECT_ID}/locations/$_KMS_KEY_LOCATION/keyRings/$_KMS_KEYRING_NAME/cryptoKeys/$_KMS_KEY_NAME/cryptoKeyVersions/$_KMS_KEY_VERSION'
      - '--artifact-url'
      - 'gcr.io/${PROJECT_ID}/helloworld:$_TAG'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - '-c'
      - gcloud container images describe us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO_NAME/test-image:$_TAG --format 'value(image_summary.digest)' > sha
    entrypoint: bash

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: 
      - run
      - --image=gcr.io/$_PROJECT_ID/helloworld:$_TAG
      - --location=$_ZONE
      - --cluster=$_CLUSTER_NAME
